[package]
license = ["Apache-2.0"]
keywords = ["Content & Files/File Management & Storage", "Cost/Freemium"]
org = "ballerinax"
name = "box"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/box"
version = "1.5.2"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
