[package]
license = ["Apache-2.0"]
keywords = ["AI/Chat", "Azure OpenAI", "Cost/Paid", "GPT-3.5", "ChatGPT", "Vendor/Microsoft"]
org = "ballerinax"
name = "azure.openai.chat"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/azure.openai.chat"
version = "2.0.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
