[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Cloud Services", "Cost/Freemium"]
org = "ballerinax"
name = "graphhopper.directions"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/graphhopper.directions"
version = "1.5.2"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
