[package]
license = ["Apache-2.0"]
keywords = ["Communication/Video Conferencing", "Cost/Freemium"]
org = "ballerinax"
name = "livestorm"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/livestorm"
version = "2.6.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
